name: run test file

on:
  push:
    branches: ["main"]
    paths: ["**.[ch]pp"]
  pull_request:
    branches: ["main"]
    paths: ["**.[ch]pp"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install dependencies
      run: make deps
    - name: test
      id: test
      run: |
        make test >> .tempfile 2>&1 || true
        cat .tempfile
        cat .tempfile | grep "Error 74" >/dev/null
        if test $? -eq 0; then echo "todo=true" >> "$GITHUB_OUTPUT"; fi
        rm .tempfile
    - name: show files
      run: make show
    - name: check for leaks
      run: make checkleaks
      if: ${{ !contains(steps.test.outputs.todo, 'true') }}
