name: run test file

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install dependencies
      run: make deps
    - name: test
      run: make test
    - name: show files
      run: make show
    - name: check for leaks
      run: make checkleaks
